### PR TITLE
Request to Merge Gian branch to Main Brench

### PR DESCRIPTION
**Pull request by Gianlucca123**
Code is working for both micro-controllers, power battery is not working well (showing the true value)

### CODE REVIEW

**Comment by jbmouret** [comment]
At first sight, there are tons of files that should not be in git (generated files, compiled files, etc.).

**Comment by Gianlucca123** [comment]
yes, it's from the ros2_ws folder, it's the work space of the UI's. I will remove them

**Comment by Gianlucca123** [comment]
Removed them, do I have to do a new pull request ?

**Comment by jbmouret** [comment]
No, no need for a different PR. The things are updated here now.

**Comment by jbmouret** [comment]
What does that mean "power battery is not working well (showing the true value)" ?

**Comment by Gianlucca123** [comment]
I have the impression the value showing on the screen is not the true level of battery, but I think it's just an impression because I took the way to calculate from the source code (the one that show when turn on the core2 for the first time). I made a function to look at the battery level each minute, I doesn't make sense calculate the level of the battery each loop. I will check if it's working as should.

**Comment by Gianlucca123** [comment]
Hello, I think it's working now, I did this in the morning, but for some reason, I was making some adjust in the UI and out of nowhere the code crashed, and I was just dealing with the UI, I stayed all day trying to discover the reason and I still don't know, I returned to the state of the last commit and my theory is I overused the same function of the UI for example setCursor and setTextColor because when I removed the ones I just added the code stop working and when I remove them it returns to normal, maybe there is some maximum of times you can call this function, I don't know. It does not make sense this problem neither my theory. I commit the changes I did, it seems to showing the battery level each minute.

**Pull request merged**
